window.DLCR_DEFAULT_CARS = [
    {
        id: 'ford-focus-st',
        title: 'Ford Focus ST',
        make: 'Ford',
        price: 19950,
        priceDisplay: '€ 19.950',
        offer: 'Betaalbare performance hatch',
        year: 2019,
        mileage: 82000,
        mileageDisplay: '82.000 km',
        power: 280,
        powerDisplay: '280 PK',
        transmission: 'Handgeschakeld',
        fuel: 'Benzine',
        drivetrain: 'FWD',
        bodyType: 'Hot hatch',
        category: 'young',
        image: 'assets/images/hero.png',
        description: 'Een leuke en betaalbare hot hatch voor jonge rijders die performance en uitstraling willen zonder meteen in het topsegment te zitten.'
    },
    {
        id: 'bmw-m4-competition',
        title: 'BMW M4 Competition',
        make: 'BMW',
        price: 65500,
        priceDisplay: '€ 65.500',
        offer: 'Performance coupe',
        year: 2021,
        mileage: 42000,
        mileageDisplay: '42.000 km',
        power: 510,
        powerDisplay: '510 PK',
        transmission: 'Automaat',
        fuel: 'Benzine',
        drivetrain: 'RWD',
        bodyType: 'Coupe',
        category: 'performance',
        image: 'assets/images/hero.png',
        description: 'Voor wie meer vermogen, uitstraling en een premium gevoel wil in een compacte maar serieuze performance coupe.'
    },
    {
        id: 'porsche-911-carrera-restored',
        title: 'Porsche 911 Carrera',
        make: 'Porsche',
        price: 89900,
        priceDisplay: '€ 89.900',
        offer: 'Restored icon',
        year: 1998,
        mileage: 120000,
        mileageDisplay: '120.000 km',
        power: 300,
        powerDisplay: '300 PK',
        transmission: 'Handgeschakeld',
        fuel: 'Benzine',
        drivetrain: 'RWD',
        bodyType: 'Coupe',
        category: 'premium',
        image: 'assets/images/restored.png',
        description: 'Een tijdloze 911 met gerestaureerde uitstraling, bedoeld voor liefhebbers die klassieke aanwezigheid willen met dagelijks karakter.'
    },
    {
        id: 'ferrari-f8-tributo',
        title: 'Ferrari F8 Tributo',
        make: 'Ferrari',
        price: 299000,
        priceDisplay: 'Op aanvraag',
        offer: 'Exotic on request',
        year: 2020,
        mileage: 12500,
        mileageDisplay: '12.500 km',
        power: 720,
        powerDisplay: '720 PK',
        transmission: 'Automaat',
        fuel: 'Benzine',
        drivetrain: 'RWD',
        bodyType: 'Supercar',
        category: 'exotic',
        image: 'assets/images/tuning.png',
        description: 'Een high-end supercar voor klanten die een uitgesproken auto willen met pure presence en serieuze performance.'
    },
    {
        id: 'lamborghini-huracan-evo',
        title: 'Lamborghini Huracán EVO',
        make: 'Lamborghini',
        price: 329000,
        priceDisplay: 'Op aanvraag',
        offer: 'Exotic delivery',
        year: 2020,
        mileage: 18000,
        mileageDisplay: '18.000 km',
        power: 640,
        powerDisplay: '640 PK',
        transmission: 'Automaat',
        fuel: 'Benzine',
        drivetrain: 'AWD',
        bodyType: 'Supercar',
        category: 'exotic',
        image: 'assets/images/tuning.png',
        description: 'Een opvallende supercar voor klanten die exclusiviteit willen zonder in te leveren op gebruiksplezier en uitstraling.'
    }
];
